#!/usr/bin/env node
/**
 * extend_typical_solutions.js
 *
 * Extinde typicalSolutions.json de la 82 → ~165 entries.
 * Lansează ca: `node scripts/extend_typical_solutions.js`
 *
 * Validare: fiecare material din layers trebuie să existe EXACT în materials.json.
 * Dacă lipsește vreo referință → opreste rularea cu raport.
 *
 * Surse autoritare:
 *   - Mc 001-2022 Tabel 2.4 / 2.7 / 2.10
 *   - C 107/0-2002, C 107/1-2005, C 107/2-2005, C 107/3-2005, C 107/5-2005
 *   - SR EN ISO 6946:2017
 *   - SR EN ISO 13370:2017 (slab on ground)
 *   - SR EN ISO 13788:2013 (condens)
 *   - P118/2013 (siguranță la foc)
 *   - Ord. MDLPA 16/2023, 348/2026
 *   - SR EN 14351-1 (uși)
 *   - PHI Passivhaus catalogue
 *   - DGNB / Minergie / EnerPHit
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SOLUTIONS_PATH = path.join(ROOT, "src/data/typicalSolutions.json");
const MATERIALS_PATH = path.join(ROOT, "src/data/materials.json");

const materials = JSON.parse(fs.readFileSync(MATERIALS_PATH, "utf-8"));
const materialNames = new Set(materials.map(m => m.name));

const existing = JSON.parse(fs.readFileSync(SOLUTIONS_PATH, "utf-8"));
const existingIds = new Set(existing.solutions.map(s => s.id));

// ── Tipologii noi (~85 entries) ──────────────────────────────────────────────

const NEW_SOLUTIONS = [
  // ════════════════════════════════════════════════════════════════════
  // PE — perete exterior — completare niche moderne și industriale
  // ════════════════════════════════════════════════════════════════════
  {
    id: "PE-icf-bloc-250-nzeb",
    elementType: "PE",
    label: "ICF (Insulating Concrete Form) 250 mm beton + 2× EPS 70 mm",
    shortLabel: "ICF 250 + EPS 2×70",
    description: "Perete tip cofraj pierdut izolat — 70 mm EPS exterior + 250 mm beton armat + 70 mm EPS interior, sistem ICF NUDURA / Logix.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.21,
    uRange: { min: 0.18, max: 0.24 },
    uClass: "B",
    fireClass: "A2-s1,d0",
    tags: ["nzeb", "icf", "rapid", "industrial"],
    source: "ETA-19/0173 (NUDURA), Mc 001-2022 Tab. 2.4",
    notes: "Construcție rapidă, masă termică internă mare, etanșeitate excelentă (n50<0.6 1/h).",
    layers: [
      { material: "Tencuială silicatică (exterior)", thickness: 5 },
      { material: "Polistiren grafitat EPS Neo", thickness: 70 },
      { material: "Beton armat", thickness: 250 },
      { material: "Polistiren grafitat EPS Neo", thickness: 70 },
      { material: "Gips-carton", thickness: 12.5 },
    ],
  },
  {
    id: "PE-rainscreen-ceramic-vm-160",
    elementType: "PE",
    label: "Fațadă ventilată placaj ceramic + VM 160 mm (rainscreen)",
    shortLabel: "Rainscreen ceramic 160",
    description: "Fațadă ventilată cu strat aer drenat 40 mm, placaj ceramic exterior pe substructură aluminiu, vată bazaltică hidrofobizată 160 mm pe perete BCA portant.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.22,
    uRange: { min: 0.19, max: 0.26 },
    uClass: "B",
    fireClass: "A1",
    tags: ["nzeb", "rainscreen", "ventilata", "comercial"],
    source: "Mc 001-2022; SR EN 13119; CWCT TN95",
    notes: "Recomandat pentru clădiri publice/comerciale ≥28 m. Strat aer drenat reduce condens.",
    layers: [
      { material: "Placaj ceramic exterior", thickness: 12 },
      { material: "Strat de aer ventilat (orice grosime)", thickness: 40 },
      { material: "Membrana inteligentă vapori (higroscopică)", thickness: 1 },
      { material: "Vată bazaltică Rockwool Frontrock MAX E", thickness: 160 },
      { material: "BCA Ytong Plus", thickness: 250 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PE-sip-panel-165-nzeb",
    elementType: "PE",
    label: "SIP (Structural Insulated Panel) — 165 mm EPS + 2× OSB",
    shortLabel: "SIP 165",
    description: "Panou structural izolat — 2× OSB18 + miez EPS 140 mm. Sistem prefabricat.",
    era: "nzeb-2020+",
    structure: "lemn",
    renovationStatus: "nou",
    uTypical: 0.27,
    uRange: { min: 0.24, max: 0.30 },
    uClass: "B",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "sip", "prefab", "rapid", "lemn"],
    source: "EOTA ETAG 003; SIPA Buildings Council",
    notes: "Subțire (165 mm) — eligibil pentru extinderi parter cu spațiu redus. Necesită ETICS exterior 80-120 mm pentru atinge nZEB strict.",
    layers: [
      { material: "Tencuială silicatică (exterior)", thickness: 5 },
      { material: "Plăci ETICS Baumit EPS-F Premium", thickness: 100 },
      { material: "OSB3 structural", thickness: 18 },
      { material: "Polistiren expandat EPS 100", thickness: 140 },
      { material: "OSB3 structural", thickness: 18 },
      { material: "Membrana inteligentă vapori (higroscopică)", thickness: 1 },
      { material: "Gips-carton", thickness: 12.5 },
    ],
  },
  {
    id: "PE-cfs-light-steel-vm-200",
    elementType: "PE",
    label: "Light steel frame (CFS) C profile + VM 200 mm",
    shortLabel: "CFS LSF VM 200",
    description: "Cadre metalice ușoare profile C (steel stud), izolație cavitate VM 200 mm, ETICS 80 mm exterior.",
    era: "nzeb-2020+",
    structure: "metal",
    renovationStatus: "nou",
    uTypical: 0.20,
    uRange: { min: 0.17, max: 0.24 },
    uClass: "B",
    fireClass: "A2-s1,d0",
    tags: ["nzeb", "lsf", "cfs", "rapid", "metal"],
    source: "EOTA ETAG 003; LSF Building Code (Romania pending)",
    notes: "Punte termică profile metalice mitigată prin ETICS continuu exterior. χ_thermal break 30%.",
    layers: [
      { material: "Tencuială silicatică (exterior)", thickness: 5 },
      { material: "Vată bazaltică Rockwool Frontrock MAX E", thickness: 80 },
      { material: "Profil oțel zincat (C/U structural)", thickness: 1.5 },
      { material: "OSB3 structural", thickness: 12 },
      { material: "Vată minerală bazaltică", thickness: 200 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Gips-carton GKBI (Knauf umiditate+foc)", thickness: 12.5 },
    ],
  },
  {
    id: "PE-cadre-ba-caramida-1965-comunist",
    elementType: "PE",
    label: "Cadru BA + zidărie cărămidă plină umplere (bloc 1960-1975)",
    shortLabel: "Cadre BA + CP 1965",
    description: "Tipic blocuri P+4 / P+10 anii 60-70 — cadre BA + zidărie cărămidă plină 25 cm umplere, fără ETICS.",
    era: "1970-1990",
    structure: "cadre-ba",
    renovationStatus: "existent",
    uTypical: 1.50,
    uRange: { min: 1.30, max: 1.70 },
    uClass: "F",
    fireClass: "A1",
    tags: ["audit", "bloc", "1960-1975", "ro-clasic"],
    source: "C 107/3-2005 Anexa A; STAS 6472/3-89",
    notes: "Canditat principal pentru anveloparea blocurilor de locuințe (PNR / Casa Verde Plus).",
    layers: [
      { material: "Tencuială mortar drișcuit (renovare)", thickness: 25 },
      { material: "Cărămidă plină", thickness: 250 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PE-cadre-ba-bca-25-bloc-1985",
    elementType: "PE",
    label: "Cadru BA + BCA 25 cm umplere (bloc 1980-1990)",
    shortLabel: "Cadre BA + BCA 25",
    description: "Bloc P+4 / P+8 cu cadre BA și BCA 25 cm umplere — anii 80, înainte de prima criză energetică reglementată RO.",
    era: "1970-1990",
    structure: "cadre-ba",
    renovationStatus: "existent",
    uTypical: 1.10,
    uRange: { min: 0.95, max: 1.25 },
    uClass: "E",
    fireClass: "A1",
    tags: ["audit", "bloc", "1980-1990", "ro-clasic"],
    source: "C 107/3-2005 Anexa A",
    notes: "Tipic perete bloc generație Crângași / Drumul Taberei / Pantelimon. Canditat reabilitare.",
    layers: [
      { material: "Tencuială mortar drișcuit (renovare)", thickness: 25 },
      { material: "BCA (beton celular autoclavizat)", thickness: 250 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PE-etics-vm-200-public-foc",
    elementType: "PE",
    label: "ETICS vată minerală 200 mm — clădire publică ≥28 m",
    shortLabel: "ETICS VM 200 foc",
    description: "ETICS conform P118/2013 pentru clădiri >28 m — exclusiv vată minerală bazaltică, conform reglementări RO foc.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.18,
    uRange: { min: 0.15, max: 0.22 },
    uClass: "A",
    fireClass: "A1",
    tags: ["nzeb", "public", "foc", "etics", "vata-minerala"],
    source: "P118/2013 art. 2.5.7; Mc 001-2022 Tab. 2.4",
    notes: "Obligatoriu A1/A2 pentru ≥28 m. Densitate VM ≥80 kg/m³ pentru ETICS.",
    layers: [
      { material: "Tencuială minerală (var+ciment+pulbere marmoră)", thickness: 5 },
      { material: "Vată bazaltică Rockwool Frontrock MAX E", thickness: 200 },
      { material: "BCA Ytong λ=0.09", thickness: 300 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PE-porotherm-50-monocaramida-nzeb",
    elementType: "PE",
    label: "Porotherm 50 T Profi monocărămidă — fără ETICS",
    shortLabel: "Porotherm 50 mono",
    description: "Cărămidă termoizolantă cu camere umplute perlit — bloc 50 cm, atinge nZEB FĂRĂ ETICS suplimentar.",
    era: "nzeb-2020+",
    structure: "zidarie",
    renovationStatus: "nou",
    uTypical: 0.21,
    uRange: { min: 0.18, max: 0.24 },
    uClass: "B",
    fireClass: "A1",
    tags: ["nzeb", "monocaramida", "porotherm", "rezidential"],
    source: "ETA-19/0247 (Wienerberger Porotherm 50 T Profi)",
    notes: "Soluție monolitică — zero punte termică în plan. Mortar termoizolant la rosturi vertical+orizontal.",
    layers: [
      { material: "Tencuială silicatică (exterior)", thickness: 8 },
      { material: "Bloc ceramic Porotherm 50 T Profi", thickness: 500 },
      { material: "Tencuială ipsos de proiecție", thickness: 15 },
    ],
  },
  {
    id: "PE-porotherm-44-mono-clasic",
    elementType: "PE",
    label: "Porotherm 44 T Profi monocărămidă (clasic 2010-2020)",
    shortLabel: "Porotherm 44 mono",
    description: "Cărămidă termoizolantă 44 cm fără ETICS — atinge U≈0.30 W/m²K, eligibilă renovare majoră.",
    era: "2010-2020",
    structure: "zidarie",
    renovationStatus: "nou",
    uTypical: 0.30,
    uRange: { min: 0.27, max: 0.34 },
    uClass: "C",
    fireClass: "A1",
    tags: ["monocaramida", "porotherm", "rezidential"],
    source: "ETA-13/0144 (Wienerberger Porotherm 44 T Profi)",
    notes: "Insuficient pentru nZEB strict 2026 — suplimentare ETICS 80-100 mm necesară pentru locuințe noi.",
    layers: [
      { material: "Tencuială silicatică (exterior)", thickness: 8 },
      { material: "Bloc ceramic Porotherm 44 T Profi", thickness: 440 },
      { material: "Tencuială ipsos de proiecție", thickness: 15 },
    ],
  },
  {
    id: "PE-vf-fibrolemn-180-eco",
    elementType: "PE",
    label: "Fațadă ventilată placaj lemn + fibrolemn 180 mm",
    shortLabel: "VF lemn fibrolemn",
    description: "Placaj larice tratat exterior + strat aer + membrană difuzie + fibrolemn rigid + cadre lemn cu fibrolemn flexibil + barieră vapori + gips-fibros.",
    era: "nzeb-2020+",
    structure: "lemn",
    renovationStatus: "nou",
    uTypical: 0.16,
    uRange: { min: 0.13, max: 0.19 },
    uClass: "A",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "ecologic", "fibrolemn", "ventilata", "naturala"],
    source: "Steico catalogue 2024; PassREg eco-walls",
    notes: "Soluție ecologică — emisii LCA ≈30% față de ETICS standard.",
    layers: [
      { material: "Larice (lariks)", thickness: 22 },
      { material: "Strat de aer ventilat (orice grosime)", thickness: 30 },
      { material: "Folie microperforată (anticondens acoperiș)", thickness: 1 },
      { material: "Fibră de lemn rigidă (fațadă)", thickness: 60 },
      { material: "Fibră de lemn flexibilă", thickness: 120 },
      { material: "Membrana inteligentă vapori (higroscopică)", thickness: 1 },
      { material: "Fermacell gips-fibros 12.5mm", thickness: 12.5 },
    ],
  },
  {
    id: "PE-modul-prefab-container-iso-retrofit",
    elementType: "PE",
    label: "Modul prefab container ISO + retrofit ETICS 100 mm",
    shortLabel: "Container retrofit",
    description: "Construcție modulară container ISO 20 ft cu retrofit termic ETICS exterior 100 mm + cavitate VM 100 mm interior.",
    era: "nzeb-2020+",
    structure: "metal",
    renovationStatus: "nou",
    uTypical: 0.24,
    uRange: { min: 0.21, max: 0.28 },
    uClass: "B",
    fireClass: "A2-s1,d0",
    tags: ["nzeb", "modular", "container", "rapid"],
    source: "ISO 6346 + EOTA ETAG 004",
    notes: "Modular eficient pentru clădiri sociale, cabane, anexe. Punte termică profile cadru semnificativă χ.",
    layers: [
      { material: "Tencuială silicatică (exterior)", thickness: 5 },
      { material: "Plăci ETICS Baumit EPS-F Premium", thickness: 100 },
      { material: "Tablă zincată", thickness: 1.5 },
      { material: "Vată minerală bazaltică", thickness: 100 },
      { material: "Profil oțel zincat (C/U structural)", thickness: 1.5 },
      { material: "Gips-carton GKBI (Knauf umiditate+foc)", thickness: 12.5 },
    ],
  },
  {
    id: "PE-double-skin-glass-comercial",
    elementType: "PE",
    label: "Fațadă dublă cu strat aer ventilat (curtain wall comercial)",
    shortLabel: "Double-skin façade",
    description: "Fațadă cortină exterioară cu strat aer ventilat 600 mm + perete interior izolat — clădiri birouri (Q PHI) >2000 m².",
    era: "nzeb-2020+",
    structure: "metal",
    renovationStatus: "nou",
    uTypical: 0.32,
    uRange: { min: 0.28, max: 0.40 },
    uClass: "C",
    fireClass: "A2-s1,d0",
    tags: ["nzeb", "double-skin", "birouri", "comercial"],
    source: "SR EN 13830; CWCT TN95",
    notes: "Necesită strategie ventilație stratificată pentru control supraîncălzire vară.",
    layers: [
      { material: "Sticlă securizată (ESG)", thickness: 8 },
      { material: "Strat de aer ventilat (orice grosime)", thickness: 600 },
      { material: "Vată bazaltică fațadă", thickness: 100 },
      { material: "Tablă aluminiu (fațadă/acoperiș)", thickness: 3 },
      { material: "Beton armat", thickness: 200 },
      { material: "Gips-carton", thickness: 12.5 },
    ],
  },
  {
    id: "PE-saxon-fachwerk-sibiu-1700",
    elementType: "PE",
    label: "Fachwerk săsesc cu umplutură lut-paie (vatră 1600-1900)",
    shortLabel: "Fachwerk Sibiu",
    description: "Casă tradițională Sibiu / Sebeș cu schelet lemn stejar + umplutură wattle and daub (cazac) cu lut și paie.",
    era: "pre1970",
    structure: "lemn",
    renovationStatus: "existent",
    uTypical: 1.60,
    uRange: { min: 1.40, max: 1.80 },
    uClass: "G",
    fireClass: "B-s2,d0",
    tags: ["audit", "vernacular", "saxon", "sibiu", "patrimoniu"],
    source: "Heritage RO Catalog; ICOMOS RO",
    notes: "Patrimoniu UNESCO — restaurare cu izolație interioară silicat de calciu compatibil higroscopic.",
    layers: [
      { material: "Tencuială lut-pleavă (clay-chaff plaster)", thickness: 30 },
      { material: "Cazac — paiantă cu nuiele și lut (wattle and daub)", thickness: 200 },
      { material: "Lemn tare (stejar)", thickness: 150 },
      { material: "Tencuială lut-pleavă (clay-chaff plaster)", thickness: 30 },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // PT — terasă plată — completare warm/cold/inverted/PV-ready
  // ════════════════════════════════════════════════════════════════════
  {
    id: "PT-terasa-pre1990-bitum",
    elementType: "PT",
    label: "Terasă plată bloc 1970-1990 — BCA + bitum (neizolată)",
    shortLabel: "Terasă bloc bitum",
    description: "Terasă tipic bloc P+4/P+8 anii 70-80 — beton 200 mm + șapă pantă 50 mm + 2 straturi carton bitumat. Foarte slab izolată termic.",
    era: "1970-1990",
    structure: "panou-mare",
    renovationStatus: "existent",
    uTypical: 1.40,
    uRange: { min: 1.20, max: 1.60 },
    uClass: "F",
    fireClass: "A1",
    tags: ["audit", "bloc", "ro-clasic", "1970-1990"],
    source: "C 107/3-2005 Anexa B; STAS 6472/3-89",
    notes: "Reabilitare PNRR / Casa Verde Plus — adăugare 200 mm EPS + membrană PVC nouă.",
    layers: [
      { material: "Bitum (membrană)", thickness: 8 },
      { material: "Mortar ciment-nisip M10", thickness: 50 },
      { material: "Beton armat", thickness: 200 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PT-terasa-vm-200-public",
    elementType: "PT",
    label: "Terasă vată bazaltică 200 mm + membrană SBS (clădire publică)",
    shortLabel: "Terasă VM 200 foc",
    description: "Terasă conform P118/2013 pentru clădiri publice și ≥28 m — vată bazaltică incombustibilă.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.18,
    uRange: { min: 0.15, max: 0.21 },
    uClass: "A",
    fireClass: "A1",
    tags: ["nzeb", "public", "foc", "vata-minerala"],
    source: "P118/2013 art. 2.5.7; SR EN 13162",
    notes: "Densitate VM ≥150 kg/m³ pentru terasă circulabilă (Rockwool Hardrock Mono).",
    layers: [
      { material: "Pietriș", thickness: 50 },
      { material: "Geotextil", thickness: 1 },
      { material: "Bitum modificat SBS", thickness: 4 },
      { material: "Vată bazaltică Rockwool Hardrock Mono", thickness: 200 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Beton armat", thickness: 200 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PT-terasa-fenolica-100-premium",
    elementType: "PT",
    label: "Terasă spumă fenolică 100 mm (premium subțire)",
    shortLabel: "Terasă fenolic 100",
    description: "Terasă cu spumă fenolică λ=0.020 — atinge U=0.20 cu doar 100 mm grosime. Premium retrofit.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "renovat",
    uTypical: 0.20,
    uRange: { min: 0.18, max: 0.23 },
    uClass: "B",
    fireClass: "B-s1,d0",
    tags: ["nzeb", "premium", "phenolic", "subtire", "retrofit"],
    source: "Kingspan Kooltherm K7 datasheet; SR EN 13166",
    notes: "Soluție pentru retrofit cu înălțare minimă a aticului (max +120 mm).",
    layers: [
      { material: "Pietriș", thickness: 50 },
      { material: "Geotextil", thickness: 1 },
      { material: "Membrană TPO/FPO", thickness: 2 },
      { material: "Kingspan Kooltherm K7 (acoperiș)", thickness: 100 },
      { material: "Bitum (membrană)", thickness: 4 },
      { material: "Beton armat", thickness: 200 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PT-terasa-foamglas-200-eternal",
    elementType: "PT",
    label: "Terasă FOAMGLAS T3+ 200 mm (durată >100 ani)",
    shortLabel: "Terasă foamglas",
    description: "Terasă cu sticlă celulară FOAMGLAS — impermeabilă, incombustibilă, indeformabilă. Soluție eternal roof.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.20,
    uRange: { min: 0.18, max: 0.23 },
    uClass: "B",
    fireClass: "A1",
    tags: ["nzeb", "premium", "foamglas", "lcc", "monumental"],
    source: "Pittsburgh Corning Datasheet 2023; ETA-13/0552",
    notes: "Recomandat pentru clădiri monumentale, muzee, terase circulabile cu trafic intens.",
    layers: [
      { material: "Dale de piatră naturală (teraso exterior)", thickness: 30 },
      { material: "Mortar ciment-nisip M10", thickness: 30 },
      { material: "Membrană bentonitică (geosynthetic clay liner)", thickness: 6 },
      { material: "Sticlă celulară T3+ (acoperiș grad)", thickness: 200 },
      { material: "Bitum (membrană)", thickness: 5 },
      { material: "Beton armat", thickness: 200 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PT-terasa-cool-roof-pv-ready",
    elementType: "PT",
    label: "Terasă cool roof reflectivă + EPS 200 (PV-ready)",
    shortLabel: "Terasă cool+PV",
    description: "Membrană albă reflectivă (TSR>0.78) + EPS 200 + ranforsare beton — pregătit pentru sistem PV pe acoperiș.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.16,
    uRange: { min: 0.14, max: 0.19 },
    uClass: "A",
    fireClass: "B-s1,d0",
    tags: ["nzeb", "cool-roof", "pv-ready", "comercial"],
    source: "SR EN 410; CRRC Cool Roof Rating Council",
    notes: "Reduce sarcină răcire vară cu 15-25%. Compatibil sisteme PV cu balast (Schletter G-2).",
    layers: [
      { material: "Acoperire elastomerică albă reflectivă", thickness: 1 },
      { material: "Strat reflectiv 'cool roof' (TSR ≥ 0.78)", thickness: 0.5 },
      { material: "Membrană TPO/FPO", thickness: 2 },
      { material: "EPS 200 (trafic greu)", thickness: 200 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Beton armat", thickness: 250 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PT-terasa-enerphit-retrofit-2x",
    elementType: "PT",
    label: "Retrofit EnerPHit terasă: + 200 EPS peste vechi 50 EPS",
    shortLabel: "Terasă EnerPHit",
    description: "Retrofit profund — membrană veche păstrată, suplimentare 200 mm EPS-G + membrană nouă PVC + protecție pietriș.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "renovat",
    uTypical: 0.13,
    uRange: { min: 0.11, max: 0.15 },
    uClass: "A+",
    fireClass: "B-s1,d0",
    tags: ["nzeb", "enerphit", "retrofit", "passivhaus", "premium"],
    source: "PHI EnerPHit standard 2025; PHI Wärmedämmsysteme",
    notes: "Soluție typ EnerPHit step-by-step retrofit. Verifică portanță suplimentară +50 kg/m².",
    layers: [
      { material: "Pietriș", thickness: 50 },
      { material: "Geotextil", thickness: 1 },
      { material: "Membrană PVC", thickness: 2 },
      { material: "Polistiren grafitat EPS Neo", thickness: 200 },
      { material: "Bitum modificat APP", thickness: 4 },
      { material: "Polistiren expandat EPS 100", thickness: 50 },
      { material: "Bitum (membrană)", thickness: 4 },
      { material: "Beton armat", thickness: 200 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PT-terasa-pir-sandwich-industrial",
    elementType: "PT",
    label: "Terasă industrială sandwich PIR 120 mm pe tablă cutată",
    shortLabel: "Terasă PIR sandwich",
    description: "Acoperiș industrial — tablă cutată oțel + barieră vapori + PIR 120 mm sandwich + membrană mecanic fixată.",
    era: "nzeb-2020+",
    structure: "metal",
    renovationStatus: "nou",
    uTypical: 0.19,
    uRange: { min: 0.17, max: 0.22 },
    uClass: "B",
    fireClass: "B-s1,d0",
    tags: ["nzeb", "industrial", "pir", "sandwich", "rapid"],
    source: "Kingspan KS1000 RW datasheet; SR EN 14509",
    notes: "Acoperiș hală producție / depozit — montaj rapid, panouri prefabricate.",
    layers: [
      { material: "Membrană TPO/FPO", thickness: 1.5 },
      { material: "Panou sandwich PIR Kingspan KS1000 RW", thickness: 120 },
      { material: "Barieră vapori folie PE+Al (compusă)", thickness: 0.3 },
      { material: "Tablă zincată", thickness: 0.75 },
    ],
  },
  {
    id: "PT-terasa-pre1990-bca-dur",
    elementType: "PT",
    label: "Terasă pre-1990 BCA armat 200 + bitum (audit)",
    shortLabel: "Terasă BCA pre1990",
    description: "Terasă bloc 1965-1985 cu plăci BCA armate (sistem Siporex) + șapă mortar + bitum. Eligibilă reabilitare PNRR.",
    era: "1970-1990",
    structure: "panou-mare",
    renovationStatus: "existent",
    uTypical: 1.05,
    uRange: { min: 0.90, max: 1.20 },
    uClass: "E",
    fireClass: "A1",
    tags: ["audit", "bloc", "siporex", "1970-1990"],
    source: "C 107/3-2005 Anexa B; STAS 8000-67",
    notes: "Plăci BCA Siporex armate — verificare carbonatare beton armat înainte retrofit.",
    layers: [
      { material: "Bitum (membrană)", thickness: 6 },
      { material: "Mortar ciment-nisip M10", thickness: 30 },
      { material: "BCA Siporex 500 (λ=0.13)", thickness: 200 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PT-terasa-circulabila-pavele",
    elementType: "PT",
    label: "Terasă circulabilă cu pavele beton + EPS 200 inversă",
    shortLabel: "Terasă inversă pavele",
    description: "Terasă inversă cu pavele beton 50 mm pe loose-laid XPS 200 mm — soluție publică pentru terase accesibile.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.18,
    uRange: { min: 0.16, max: 0.21 },
    uClass: "A",
    fireClass: "A2-s1,d0",
    tags: ["nzeb", "circulabila", "inversa", "public"],
    source: "Mc 001-2022 + factor f drainage corecție 0.04 W/m²K",
    notes: "Coeficient corecție Δf=0.04 W/m²K pentru pierderi prin precipitații (ISO 6946 Annex F).",
    layers: [
      { material: "Pavele beton (pavaj)", thickness: 50 },
      { material: "Pietriș", thickness: 30 },
      { material: "Geotextil", thickness: 1 },
      { material: "XPS 400 kPa (inversă, λ=0.035)", thickness: 200 },
      { material: "Membrană PVC", thickness: 2 },
      { material: "Mortar ciment-nisip M10", thickness: 30 },
      { material: "Beton armat", thickness: 200 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // PA — acoperiș înclinat — completare lemn modern și industrial
  // ════════════════════════════════════════════════════════════════════
  {
    id: "PA-saltea-vm-rulou-200-clasic",
    elementType: "PA",
    label: "Acoperiș înclinat saltea VM rulou 200 mm — căpriori 50 cm",
    shortLabel: "PA saltea VM 200",
    description: "Acoperiș lemn cu vată minerală sticlă rulou 200 mm între căpriori 80×200 mm la pas 50 cm.",
    era: "1990-2010",
    structure: "lemn",
    renovationStatus: "existent",
    uTypical: 0.32,
    uRange: { min: 0.28, max: 0.38 },
    uClass: "C",
    fireClass: "B-s2,d0",
    tags: ["audit", "lemn", "1990-2010", "popular"],
    source: "C 107/2-2005 Anexa A; STAS 11506-87",
    notes: "Tipic case 1990-2010 — punte termică căpriori χ=12% suprafață, U efectiv +15% față de central.",
    layers: [
      { material: "Membrană EPDM", thickness: 0.8 },
      { material: "Folie microperforată (anticondens acoperiș)", thickness: 0.8 },
      { material: "Strat de aer ventilat (orice grosime)", thickness: 40 },
      { material: "Saltea vată sticlă (mansardă orizontal)", thickness: 200 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Gips-carton", thickness: 12.5 },
    ],
  },
  {
    id: "PA-clt-3l-100-sarking-160",
    elementType: "PA",
    label: "Acoperiș CLT 100 mm + sarking fibrolemn 160 mm (Passivhaus)",
    shortLabel: "PA CLT 100 + sarking",
    description: "Panou CLT 3 straturi structural + sarking fibrolemn rigid extern. Eliminare totală punte termică căpriori.",
    era: "nzeb-2020+",
    structure: "lemn",
    renovationStatus: "nou",
    uTypical: 0.13,
    uRange: { min: 0.11, max: 0.15 },
    uClass: "A+",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "passivhaus", "clt", "sarking", "premium"],
    source: "PHI Component Database 2024; SR EN 16351",
    notes: "Continuitate higroscopică — verificare condens interstițial conform SR EN ISO 13788.",
    layers: [
      { material: "Strat de aer ventilat (orice grosime)", thickness: 40 },
      { material: "Folie microperforată (anticondens acoperiș)", thickness: 1 },
      { material: "Fibră de lemn rigidă acoperiș (Sarking)", thickness: 160 },
      { material: "Barieră vapori aluminiu", thickness: 0.3 },
      { material: "CLT (Cross Laminated Timber)", thickness: 100 },
    ],
  },
  {
    id: "PA-shed-uniform-pir-100",
    elementType: "PA",
    label: "Acoperiș shed uniform sandwich PIR 100 mm — hală producție",
    shortLabel: "Shed PIR 100",
    description: "Acoperiș hală industrială tipic shed — tablă cutată + sandwich PIR 100 mm fixat mecanic.",
    era: "nzeb-2020+",
    structure: "metal",
    renovationStatus: "nou",
    uTypical: 0.22,
    uRange: { min: 0.20, max: 0.26 },
    uClass: "B",
    fireClass: "B-s1,d0",
    tags: ["nzeb", "industrial", "pir", "rapid"],
    source: "SR EN 14509; ETA-15/0119 Metecno",
    notes: "Hală producție — pantă 10-15° pentru drenaj. Atenție condens dedesubt când rost cumulează > 6 cm.",
    layers: [
      { material: "Panou sandwich PIR Metecno (acoperiș)", thickness: 100 },
    ],
  },
  {
    id: "PA-fibrolemn-240-eco",
    elementType: "PA",
    label: "Acoperiș înclinat fibră de lemn 240 mm (eco-Passivhaus)",
    shortLabel: "PA fibrolemn 240",
    description: "Acoperiș Passivhaus ecologic — fibră de lemn flexibilă între căpriori + sarking. Toate naturale.",
    era: "nzeb-2020+",
    structure: "lemn",
    renovationStatus: "nou",
    uTypical: 0.13,
    uRange: { min: 0.12, max: 0.15 },
    uClass: "A+",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "passivhaus", "ecologic", "fibrolemn"],
    source: "Steico Universal datasheet; PassREg",
    notes: "Lambdă=0.040, masă termică ridicată — protecție vară excelentă (Φ_v_2h<3°C).",
    layers: [
      { material: "Strat de aer ventilat (orice grosime)", thickness: 40 },
      { material: "Folie microperforată (anticondens acoperiș)", thickness: 1 },
      { material: "Fibră de lemn rigidă Steico Universal", thickness: 60 },
      { material: "Fibră de lemn flexibilă", thickness: 240 },
      { material: "Membrana inteligentă vapori (higroscopică)", thickness: 0.3 },
      { material: "Plăci celuloză rigide (Homatherm/Steico-class)", thickness: 25 },
      { material: "Gips-carton", thickness: 12.5 },
    ],
  },
  {
    id: "PA-vm-ph-saltea-300-acm",
    elementType: "PA",
    label: "Acoperiș Passivhaus saltea VM 300 mm + sarking",
    shortLabel: "PA VM 300 PH",
    description: "Acoperiș Passivhaus cu vată minerală bazaltică 300 mm între căpriori + 60 mm sarking VM rigid.",
    era: "nzeb-2020+",
    structure: "lemn",
    renovationStatus: "nou",
    uTypical: 0.12,
    uRange: { min: 0.10, max: 0.14 },
    uClass: "A+",
    fireClass: "A1",
    tags: ["nzeb", "passivhaus", "vata-minerala", "foc"],
    source: "PHI Component Database 2024",
    notes: "Variantă incombustibilă (A1) pentru locuințe înalte sau publice cu structură lemn.",
    layers: [
      { material: "Strat de aer ventilat (orice grosime)", thickness: 40 },
      { material: "Folie microperforată (anticondens acoperiș)", thickness: 1 },
      { material: "Vată bazaltică acoperiș", thickness: 60 },
      { material: "Vată bazaltică Rockwool Flexi (între căpriori)", thickness: 300 },
      { material: "Membrana inteligentă vapori (higroscopică)", thickness: 0.3 },
      { material: "Gips-carton", thickness: 12.5 },
    ],
  },
  {
    id: "PA-pir-100-mansarda-subtire",
    elementType: "PA",
    label: "Mansardă subțire PIR 100 mm — retrofit cu spațiu redus",
    shortLabel: "PA PIR 100 retrofit",
    description: "Soluție mansardă cu spațiu interior redus — PIR 100 mm + 50 mm fibrolemn extern. Atinge U≈0.17 la 150 mm total.",
    era: "nzeb-2020+",
    structure: "lemn",
    renovationStatus: "renovat",
    uTypical: 0.17,
    uRange: { min: 0.15, max: 0.20 },
    uClass: "A",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "retrofit", "pir", "subtire"],
    source: "Kingspan TEK Building System; Kooltherm K7",
    notes: "Recomandat retrofit case existente unde înălțarea acoperișului nu e fezabilă.",
    layers: [
      { material: "Strat de aer ventilat (orice grosime)", thickness: 40 },
      { material: "Folie microperforată (anticondens acoperiș)", thickness: 1 },
      { material: "Fibră de lemn rigidă (fațadă)", thickness: 50 },
      { material: "PIR cu folie alu", thickness: 100 },
      { material: "Barieră vapori aluminiu", thickness: 0.3 },
      { material: "Gips-carton RF (Rigips rezistent foc 12.5mm)", thickness: 12.5 },
    ],
  },
  {
    id: "PA-mansarda-pre1990-vm-50",
    elementType: "PA",
    label: "Mansardă pre-1990 — saltea VM 50 mm între căpriori (audit)",
    shortLabel: "PA pre1990 VM 50",
    description: "Mansardă veche cu izolație minimă VM 50 mm între căpriori — necesită retrofit.",
    era: "1970-1990",
    structure: "lemn",
    renovationStatus: "existent",
    uTypical: 0.85,
    uRange: { min: 0.70, max: 1.00 },
    uClass: "E",
    fireClass: "B-s2,d0",
    tags: ["audit", "lemn", "1970-1990", "ro-clasic"],
    source: "C 107/2-1995 Anexa A",
    notes: "Tipic case 1970-1990 — energie pierdută major prin acoperiș (40-50% loss).",
    layers: [
      { material: "Membrană EPDM", thickness: 0.8 },
      { material: "Strat de aer ventilat (orice grosime)", thickness: 40 },
      { material: "Vată minerală bazaltică", thickness: 50 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Scânduri (sheathing boarding)", thickness: 22 },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // PM — mansardă (plan înclinat) — completare diverse generații
  // ════════════════════════════════════════════════════════════════════
  {
    id: "PM-cleste-pre1900-fan",
    elementType: "PM",
    label: "Mansardă cu clește lemn + fân pod pre-1900 (vernacular)",
    shortLabel: "PM cleste fân",
    description: "Mansardă tradițională rurală RO — schelet lemn cu clește (king post truss) + umplutură fân pod natural.",
    era: "pre1970",
    structure: "lemn",
    renovationStatus: "existent",
    uTypical: 0.95,
    uRange: { min: 0.80, max: 1.10 },
    uClass: "E",
    fireClass: "F",
    tags: ["audit", "vernacular", "lemn", "rural", "patrimoniu"],
    source: "Heritage RO Catalog; Vernacular timber",
    notes: "Risc foc ridicat (clasa F) — retrofit obligatoriu cu izolație incombustibilă.",
    layers: [
      { material: "Bârne lemn brut horizontal (blockhaus traditional)", thickness: 80 },
      { material: "Fân de pod (hay attic insulation, vernacular)", thickness: 200 },
      { material: "Scânduri (sheathing boarding)", thickness: 25 },
    ],
  },
  {
    id: "PM-vm-150-2010-clasic",
    elementType: "PM",
    label: "Mansardă VM 150 mm 2010-2020 (clasic post-Mc 001)",
    shortLabel: "PM VM 150",
    description: "Mansardă tipică case 2010-2020 cu vată minerală 150 mm — atinge U≈0.30 W/m²K.",
    era: "2010-2020",
    structure: "lemn",
    renovationStatus: "existent",
    uTypical: 0.30,
    uRange: { min: 0.27, max: 0.35 },
    uClass: "C",
    fireClass: "B-s2,d0",
    tags: ["audit", "2010-2020", "lemn", "popular"],
    source: "C 107/3-2005; Mc 001-2006 Tab. 2.4",
    notes: "Insuficient pentru nZEB strict 2026 — necesită +100 mm sarking sau saltea ușoară pe inferior.",
    layers: [
      { material: "Membrană EPDM", thickness: 0.8 },
      { material: "Strat de aer ventilat (orice grosime)", thickness: 40 },
      { material: "Folie microperforată (anticondens acoperiș)", thickness: 1 },
      { material: "Vată minerală bazaltică", thickness: 150 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Gips-carton", thickness: 12.5 },
    ],
  },
  {
    id: "PM-cellulose-300-eco-nzeb",
    elementType: "PM",
    label: "Mansardă celuloză insuflată 300 mm (eco-PH)",
    shortLabel: "PM cellulose 300",
    description: "Mansardă Passivhaus ecologică cu celuloză insuflată 300 mm — masă termică ridicată, protecție vară.",
    era: "nzeb-2020+",
    structure: "lemn",
    renovationStatus: "nou",
    uTypical: 0.12,
    uRange: { min: 0.10, max: 0.14 },
    uClass: "A+",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "passivhaus", "ecologic", "celuloza"],
    source: "Isocell GmbH; PassREg",
    notes: "Insuflare nivel densitate min. 50 kg/m³ pentru evitare tasare. Verificare uzură 5-7 ani.",
    layers: [
      { material: "Strat de aer ventilat (orice grosime)", thickness: 40 },
      { material: "Folie microperforată (anticondens acoperiș)", thickness: 1 },
      { material: "Fibră de lemn rigidă acoperiș (Sarking)", thickness: 60 },
      { material: "Celuloză insuflată", thickness: 300 },
      { material: "Membrana inteligentă vapori (higroscopică)", thickness: 0.3 },
      { material: "Gips-carton", thickness: 12.5 },
    ],
  },
  {
    id: "PM-fibrolemn-280-ph",
    elementType: "PM",
    label: "Mansardă fibrolemn 280 mm (Passivhaus woodfibre)",
    shortLabel: "PM fibrolemn 280",
    description: "Mansardă Passivhaus fibră de lemn 280 mm — soluție 100% naturală cu protecție vară excelentă.",
    era: "nzeb-2020+",
    structure: "lemn",
    renovationStatus: "nou",
    uTypical: 0.13,
    uRange: { min: 0.11, max: 0.16 },
    uClass: "A+",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "passivhaus", "ecologic", "fibrolemn"],
    source: "Steico Universal; PHI Component Database",
    notes: "TFA (Time Lag Factor) ridicat — întârzâie căldura solară 10-12h.",
    layers: [
      { material: "Strat de aer ventilat (orice grosime)", thickness: 40 },
      { material: "Folie microperforată (anticondens acoperiș)", thickness: 1 },
      { material: "Fibră de lemn rigidă acoperiș (Sarking)", thickness: 60 },
      { material: "Fibră de lemn flexibilă", thickness: 220 },
      { material: "Membrana inteligentă vapori (higroscopică)", thickness: 0.3 },
      { material: "Plăci celuloză rigide (Homatherm/Steico-class)", thickness: 25 },
      { material: "Gips-carton", thickness: 12.5 },
    ],
  },
  {
    id: "PM-mixt-cadre-ba-vm-200",
    elementType: "PM",
    label: "Mansardă structură mixtă cadre BA + VM 200 mm",
    shortLabel: "PM mixt BA VM",
    description: "Mansardă cu structură planșeu BA + VM 200 mm — bloc apartamente penultim nivel.",
    era: "2010-2020",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.21,
    uRange: { min: 0.19, max: 0.25 },
    uClass: "B",
    fireClass: "A1",
    tags: ["nzeb", "mixt", "bloc", "vata-minerala"],
    source: "Mc 001-2022 Tab. 2.4",
    notes: "Variantă bloc multifamilial cu mansardă utilă (apartament tip dublex).",
    layers: [
      { material: "Membrană EPDM", thickness: 1 },
      { material: "Strat de aer ventilat (orice grosime)", thickness: 40 },
      { material: "Vată bazaltică Rockwool Hardrock Mono", thickness: 200 },
      { material: "Beton armat", thickness: 150 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // PP — sub pod neîncălzit — completare blow-in moderne
  // ════════════════════════════════════════════════════════════════════
  {
    id: "PP-pod-cellulose-blow-300-nzeb",
    elementType: "PP",
    label: "Pod neîncălzit celuloză insuflată 300 mm (nZEB)",
    shortLabel: "PP cellulose 300",
    description: "Planșeu pod cu celuloză insuflată 300 mm — soluție rapidă nZEB pentru retrofit case existente.",
    era: "nzeb-2020+",
    structure: "zidarie",
    renovationStatus: "renovat",
    uTypical: 0.13,
    uRange: { min: 0.11, max: 0.16 },
    uClass: "A+",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "retrofit", "celuloza", "rapid"],
    source: "Isocell GmbH; PassREg",
    notes: "Suflată în 1 zi pentru o casă tipică. Densitate 35 kg/m³ pentru pod accesibil ocazional.",
    layers: [
      { material: "Celuloză insuflată", thickness: 300 },
      { material: "Folie microperforată (anticondens acoperiș)", thickness: 0.3 },
      { material: "Beton armat", thickness: 150 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PP-pod-paie-traditional",
    elementType: "PP",
    label: "Pod tradițional paie compactate (vernacular RO)",
    shortLabel: "PP paie tradițional",
    description: "Pod case rurale tradiționale cu paie comprimate 250-400 mm — izolație vernaculară RO.",
    era: "pre1970",
    structure: "zidarie",
    renovationStatus: "existent",
    uTypical: 0.30,
    uRange: { min: 0.25, max: 0.40 },
    uClass: "C",
    fireClass: "F",
    tags: ["audit", "vernacular", "paie", "rural", "patrimoniu"],
    source: "Heritage RO Catalog",
    notes: "Surprinzător de eficient termic, dar risc foc major. Restaurare cu fân tratat ignifug.",
    layers: [
      { material: "Paie comprimate", thickness: 350 },
      { material: "Argilă uscată", thickness: 50 },
      { material: "Scânduri (sheathing boarding)", thickness: 25 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PP-pod-vata-rulou-200-clasic",
    elementType: "PP",
    label: "Pod vată sticlă rulou 200 mm (clasic 2010-2020)",
    shortLabel: "PP rulou 200",
    description: "Planșeu pod cu saltea VM rulou orizontal 200 mm — soluție populară 2010-2020.",
    era: "2010-2020",
    structure: "zidarie",
    renovationStatus: "existent",
    uTypical: 0.20,
    uRange: { min: 0.18, max: 0.24 },
    uClass: "B",
    fireClass: "A1",
    tags: ["audit", "2010-2020", "vata-minerala", "popular"],
    source: "Isover Multimax 30 datasheet; Mc 001-2006",
    notes: "Insuficient nZEB strict — adăugare 150 mm pentru renovare majoră.",
    layers: [
      { material: "Vată minerală de sticlă Isover Multimax 30", thickness: 200 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Beton armat", thickness: 150 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PP-pod-eps-150-zid",
    elementType: "PP",
    label: "Pod EPS 150 mm pe planșeu beton (case interbelice retrofit)",
    shortLabel: "PP EPS 150",
    description: "Pod retrofit case 1920-1950 — adăugare EPS 150 mm peste planșeu beton existent.",
    era: "2010-2020",
    structure: "zidarie",
    renovationStatus: "renovat",
    uTypical: 0.22,
    uRange: { min: 0.20, max: 0.27 },
    uClass: "B",
    fireClass: "B-s2,d0",
    tags: ["audit", "retrofit", "eps", "interbelic"],
    source: "Mc 001-2022 Tab. 2.4",
    notes: "Pod accesibil ocazional — protecție mecanică OSB necesară.",
    layers: [
      { material: "OSB3 structural", thickness: 18 },
      { material: "Polistiren expandat EPS 100", thickness: 150 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Beton armat", thickness: 150 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PP-pod-vata-blow-350-premium",
    elementType: "PP",
    label: "Pod vată sticlă insuflată 350 mm (premium)",
    shortLabel: "PP blow 350",
    description: "Planșeu pod cu vată sticlă insuflată 350 mm — soluție premium pentru clădiri publice și nZEB.",
    era: "nzeb-2020+",
    structure: "zidarie",
    renovationStatus: "renovat",
    uTypical: 0.11,
    uRange: { min: 0.09, max: 0.14 },
    uClass: "A+",
    fireClass: "A1",
    tags: ["nzeb", "premium", "blow-in", "vata-sticla"],
    source: "Isover Insulsafe SP; SR EN 14064",
    notes: "Densitate 18 kg/m³, lambda=0.034. Verificare etanșeitate cu blower door.",
    layers: [
      { material: "Vată de sticlă insuflată (attic blown)", thickness: 350 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Beton armat", thickness: 150 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // PB — peste subsol neîncălzit — completare diverse epoci
  // ════════════════════════════════════════════════════════════════════
  {
    id: "PB-pre1990-neizolat",
    elementType: "PB",
    label: "Planșeu peste subsol pre-1990 — beton 150 mm + parchet (audit)",
    shortLabel: "PB pre1990",
    description: "Planșeu deasupra subsol neîncălzit case 1900-1990 — beton 150 mm + finisaj parchet, fără izolație.",
    era: "pre1970",
    structure: "zidarie",
    renovationStatus: "existent",
    uTypical: 1.95,
    uRange: { min: 1.70, max: 2.20 },
    uClass: "G",
    fireClass: "A1",
    tags: ["audit", "pre-1970", "ro-clasic"],
    source: "C 107/3-2005 Anexa A",
    notes: "Surse pierderi termice majore — eligibil retrofit cu PIR sub planșeu.",
    layers: [
      { material: "Parchet lemn", thickness: 22 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Mortar ciment-nisip M10", thickness: 30 },
      { material: "Beton armat", thickness: 150 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PB-XPS-100-traffic-garaj",
    elementType: "PB",
    label: "PB peste garaj XPS 100 mm sub placă (auto-trafic)",
    shortLabel: "PB XPS 100 garaj",
    description: "Planșeu peste garaj cu XPS 100 mm rezistent compresie sub placă beton — vehicul mediu.",
    era: "1990-2010",
    structure: "cadre-ba",
    renovationStatus: "existent",
    uTypical: 0.32,
    uRange: { min: 0.28, max: 0.37 },
    uClass: "C",
    fireClass: "A2-s1,d0",
    tags: ["audit", "garaj", "xps", "auto"],
    source: "Mc 001-2006 Tab. 2.4",
    notes: "XPS 300 kPa — adecvat trafic vehicul ușor (max 3.5 t).",
    layers: [
      { material: "Parchet stratificat", thickness: 14 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Șapă autonivelantă", thickness: 50 },
      { material: "XPS 300 (fundații)", thickness: 100 },
      { material: "Beton armat", thickness: 150 },
      { material: "Tencuială ipsos de proiecție", thickness: 15 },
    ],
  },
  {
    id: "PB-eps-150-clasic-retrofit",
    elementType: "PB",
    label: "PB EPS 150 mm peste subsol — retrofit 2010-2020",
    shortLabel: "PB EPS 150",
    description: "Planșeu deasupra subsol neîncălzit retrofitat — EPS 150 mm sub placă beton.",
    era: "2010-2020",
    structure: "zidarie",
    renovationStatus: "renovat",
    uTypical: 0.22,
    uRange: { min: 0.20, max: 0.27 },
    uClass: "B",
    fireClass: "A2-s1,d0",
    tags: ["retrofit", "eps", "popular", "renovare-majora"],
    source: "Mc 001-2022 Tab. 2.4",
    notes: "Tipic renovare majoră 2010-2020 case interbelice.",
    layers: [
      { material: "Parchet lemn", thickness: 22 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Șapă autonivelantă", thickness: 50 },
      { material: "Polistiren expandat EPS 100", thickness: 150 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Beton armat", thickness: 200 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PB-vm-200-foc-public",
    elementType: "PB",
    label: "PB peste subsol vată minerală 200 mm — clădire publică",
    shortLabel: "PB VM 200 foc",
    description: "Planșeu peste subsol cu vată minerală bazaltică 200 mm pentru clădiri publice (P118).",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.18,
    uRange: { min: 0.15, max: 0.22 },
    uClass: "A",
    fireClass: "A1",
    tags: ["nzeb", "public", "foc", "vata-minerala"],
    source: "P118/2013 art. 2.5.7; Mc 001-2022",
    notes: "Densitate VM ≥80 kg/m³ pentru sub planșeu (compresie redusă).",
    layers: [
      { material: "Gresie ceramică", thickness: 10 },
      { material: "Mortar adeziv", thickness: 5 },
      { material: "Șapă autonivelantă", thickness: 60 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Vată bazaltică HD", thickness: 200 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Beton armat", thickness: 200 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PB-foamglas-200-monumental",
    elementType: "PB",
    label: "PB FOAMGLAS 200 mm — clădiri monumentale (durată >100 ani)",
    shortLabel: "PB foamglas",
    description: "Planșeu peste subsol cu sticlă celulară FOAMGLAS — soluție monumentală indeformabilă.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.21,
    uRange: { min: 0.19, max: 0.24 },
    uClass: "B",
    fireClass: "A1",
    tags: ["nzeb", "premium", "foamglas", "monumental"],
    source: "Pittsburgh Corning Catalogue 2023",
    notes: "Indicat sub planșeu cu trafic intens — incompresibil, nu absoarbe apa.",
    layers: [
      { material: "Dale de piatră naturală (teraso exterior)", thickness: 30 },
      { material: "Mortar de pozare gresie (M15)", thickness: 30 },
      { material: "Sticlă celulară Floor (placă, comprimare 1.6 N/mm²)", thickness: 200 },
      { material: "Bitum (membrană)", thickness: 5 },
      { material: "Beton armat", thickness: 200 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PB-grinzi-bca-vata-150",
    elementType: "PB",
    label: "PB grinzi BCA + VM 150 mm (bloc 1985)",
    shortLabel: "PB BCA VM 150",
    description: "Planșeu peste subsol bloc cu grinzi BCA armate (Siporex) + retrofit vată minerală 150 mm.",
    era: "1970-1990",
    structure: "panou-mare",
    renovationStatus: "renovat",
    uTypical: 0.28,
    uRange: { min: 0.25, max: 0.33 },
    uClass: "C",
    fireClass: "A1",
    tags: ["bloc", "siporex", "1970-1990", "renovat"],
    source: "C 107/3-2005 Anexa A",
    notes: "Bloc tipic anii 80 — Siporex 200 mm armat + vată retrofit.",
    layers: [
      { material: "Parchet stratificat", thickness: 14 },
      { material: "Mortar ciment-nisip M10", thickness: 50 },
      { material: "BCA Siporex 500 (λ=0.13)", thickness: 200 },
      { material: "Vată minerală bazaltică", thickness: 150 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // PL — placă pe sol — completare epoci și sisteme moderne
  // ════════════════════════════════════════════════════════════════════
  {
    id: "PL-pre1970-piatra-nisip",
    elementType: "PL",
    label: "Placă pe sol pre-1970 — piatră de râu + nisip (case rurale)",
    shortLabel: "PL pre1970 piatră",
    description: "Placă tradițională rurală RO — piatră de râu așezată în nisip, fără izolație.",
    era: "pre1970",
    structure: "zidarie",
    renovationStatus: "existent",
    uTypical: 1.20,
    uRange: { min: 1.00, max: 1.45 },
    uClass: "F",
    fireClass: "A1",
    tags: ["audit", "vernacular", "rural", "pre-1970"],
    source: "C 107/5-2005 Anexa A; vernacular RO",
    notes: "Piatră așezată direct pe sol — eligibil retrofit XPS 100 mm sub placă nouă.",
    layers: [
      { material: "Piatră de calcar (calc. compactat)", thickness: 100 },
      { material: "Nisip uscat", thickness: 100 },
      { material: "Sol (pământ)", thickness: 500 },
    ],
  },
  {
    id: "PL-eps-100-clasic-2000",
    elementType: "PL",
    label: "Placă pe sol EPS 100 mm — case 2000-2010 clasic",
    shortLabel: "PL EPS 100 clasic",
    description: "Placă pe sol case construite 2000-2010 cu EPS 100 mm sub șapă — atinge U≈0.30 W/m²K.",
    era: "1990-2010",
    structure: "zidarie",
    renovationStatus: "existent",
    uTypical: 0.30,
    uRange: { min: 0.27, max: 0.34 },
    uClass: "C",
    fireClass: "A1",
    tags: ["audit", "1990-2010", "popular"],
    source: "C 107/5-2005",
    notes: "Insuficient nZEB 2026 — necesar retrofit cu placă suplimentară izolată sau XPS perimetru.",
    layers: [
      { material: "Gresie ceramică", thickness: 10 },
      { material: "Mortar adeziv", thickness: 5 },
      { material: "Șapă autonivelantă", thickness: 50 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Polistiren expandat EPS 100", thickness: 100 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Beton armat", thickness: 100 },
      { material: "Pietriș nisipos (compactat)", thickness: 200 },
    ],
  },
  {
    id: "PL-xps-200-ph-perimetru",
    elementType: "PL",
    label: "Placă pe sol XPS 200 mm + centură perimetru (Passivhaus)",
    shortLabel: "PL XPS 200 PH",
    description: "Placă Passivhaus cu XPS 200 mm + centură perimetrală XPS 100 mm — eliminare punte termică perimetru.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.13,
    uRange: { min: 0.11, max: 0.16 },
    uClass: "A+",
    fireClass: "A1",
    tags: ["nzeb", "passivhaus", "premium"],
    source: "PHI Component Database; SR EN ISO 13370",
    notes: "Centură XPS perimetru 60 cm coboară Ψ_perimetru de la 0.45 la 0.05 W/(m·K).",
    layers: [
      { material: "Parchet stratificat", thickness: 14 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Șapă autonivelantă", thickness: 70 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Polistiren grafitat EPS Neo", thickness: 200 },
      { material: "Membrană bentonitică (geosynthetic clay liner)", thickness: 6 },
      { material: "Beton armat", thickness: 150 },
      { material: "Pietriș nisipos (compactat)", thickness: 300 },
    ],
  },
  {
    id: "PL-foamglas-200-eternal",
    elementType: "PL",
    label: "Placă pe sol FOAMGLAS 200 mm (clădiri monumentale)",
    shortLabel: "PL foamglas",
    description: "Placă pe sol cu sticlă celulară FOAMGLAS — durată >100 ani, indeformabilă.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.18,
    uRange: { min: 0.16, max: 0.21 },
    uClass: "A",
    fireClass: "A1",
    tags: ["nzeb", "premium", "foamglas", "monumental"],
    source: "Pittsburgh Corning Catalogue 2023",
    notes: "Foamglas — bariera vapori încorporată. Indicat clădiri patrimoniu.",
    layers: [
      { material: "Dale de piatră naturală (teraso exterior)", thickness: 30 },
      { material: "Mortar de pozare gresie (M15)", thickness: 30 },
      { material: "Beton armat", thickness: 100 },
      { material: "Sticlă celulară Floor (placă, comprimare 1.6 N/mm²)", thickness: 200 },
      { material: "Bitum (membrană)", thickness: 5 },
      { material: "Beton armat", thickness: 100 },
      { material: "Pietriș nisipos (compactat)", thickness: 300 },
    ],
  },
  {
    id: "PL-eps-igloo-160-ufh-eco",
    elementType: "PL",
    label: "Placă pe sol cu sistem Igloo + UFH 160 mm",
    shortLabel: "PL Igloo UFH",
    description: "Sistem Cupolex/Igloo cu spațiu aer ventilat sub placă + EPS Igloo special UFH + șapă tradițional.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.20,
    uRange: { min: 0.18, max: 0.23 },
    uClass: "B",
    fireClass: "A1",
    tags: ["nzeb", "ufh", "igloo", "antiradon"],
    source: "Cupolex datasheet; protezione antiradon RO",
    notes: "Sistem ventilat sub placă — protecție anti-radon 222Rn (relevantă RO Cluj/Banat).",
    layers: [
      { material: "Parchet stratificat", thickness: 14 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Șapă autonivelantă", thickness: 70 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "EPS Igloo (pardoseală radiante, λ=0.038)", thickness: 160 },
      { material: "Beton armat", thickness: 100 },
      { material: "Strat de aer ventilat (orice grosime)", thickness: 250 },
      { material: "Pietriș nisipos (compactat)", thickness: 200 },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // PV — peste pasaj/exterior — completare situații
  // ════════════════════════════════════════════════════════════════════
  {
    id: "PV-pasaj-XPS-150-clasic",
    elementType: "PV",
    label: "Planșeu peste pasaj XPS 150 mm + tencuială siliconică",
    shortLabel: "PV pasaj XPS 150",
    description: "Planșeu deasupra pasaj deschis (intrare bloc) cu XPS 150 mm sub planșeu beton.",
    era: "2010-2020",
    structure: "cadre-ba",
    renovationStatus: "renovat",
    uTypical: 0.24,
    uRange: { min: 0.22, max: 0.29 },
    uClass: "B",
    fireClass: "A2-s1,d0",
    tags: ["retrofit", "pasaj", "xps", "popular"],
    source: "Mc 001-2022 Tab. 2.4",
    notes: "XPS exterior pe față inferioară planșeu — protecție mecanică plasă armare + tencuială.",
    layers: [
      { material: "Parchet stratificat", thickness: 14 },
      { material: "Mortar ciment-nisip M10", thickness: 50 },
      { material: "Beton armat", thickness: 200 },
      { material: "XPS 200 kPa (fundații ușoare, λ=0.034)", thickness: 150 },
      { material: "Tencuială siliconică (exterior)", thickness: 5 },
    ],
  },
  {
    id: "PV-pasaj-VM-200-public",
    elementType: "PV",
    label: "PV pasaj vată minerală 200 mm (clădire publică)",
    shortLabel: "PV VM 200 foc",
    description: "Planșeu peste pasaj cu vată bazaltică 200 mm — clădiri publice cu reglementare foc P118.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.18,
    uRange: { min: 0.16, max: 0.22 },
    uClass: "A",
    fireClass: "A1",
    tags: ["nzeb", "public", "foc", "vata-minerala"],
    source: "P118/2013; Mc 001-2022",
    notes: "VM ≥130 kg/m³ pentru față inferioară pasaj (vânt + impact mecanic).",
    layers: [
      { material: "Parchet lemn", thickness: 22 },
      { material: "Mortar ciment-nisip M10", thickness: 50 },
      { material: "Beton armat", thickness: 200 },
      { material: "Vată bazaltică Rockwool Hardrock Mono", thickness: 200 },
      { material: "Tencuială silicatică (exterior)", thickness: 5 },
    ],
  },
  {
    id: "PV-balcon-cantilever-pir-120",
    elementType: "PV",
    label: "Balcon consolă PIR 120 mm + plasă armare",
    shortLabel: "PV balcon PIR",
    description: "Planșeu balcon consolă (cantilever) cu PIR 120 mm sub și parchet exterior deasupra.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.22,
    uRange: { min: 0.20, max: 0.27 },
    uClass: "B",
    fireClass: "B-s1,d0",
    tags: ["nzeb", "balcon", "pir", "rezidential"],
    source: "Mc 001-2022; ETA Schöck Isokorb",
    notes: "Conexiune cu interior prin Schöck Isokorb pentru reducere punte termică Ψ.",
    layers: [
      { material: "Pavele beton (pavaj)", thickness: 30 },
      { material: "Mortar ciment-nisip M10", thickness: 30 },
      { material: "Membrană EPDM", thickness: 1 },
      { material: "Beton armat", thickness: 150 },
      { material: "PIR cu folie alu", thickness: 120 },
      { material: "Tencuială silicatică (exterior)", thickness: 5 },
    ],
  },
  {
    id: "PV-foamglas-150-monumental",
    elementType: "PV",
    label: "PV pasaj FOAMGLAS 150 mm (clădiri monumentale)",
    shortLabel: "PV foamglas",
    description: "Planșeu peste pasaj clădire publică cu FOAMGLAS 150 mm — durată >100 ani, complet incombustibil.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.27,
    uRange: { min: 0.24, max: 0.31 },
    uClass: "C",
    fireClass: "A1",
    tags: ["nzeb", "premium", "foamglas", "monumental"],
    source: "Pittsburgh Corning Catalogue 2023",
    notes: "Indeformabil + impermeabil + incombustibil — soluție monumentală.",
    layers: [
      { material: "Parchet lemn", thickness: 22 },
      { material: "Mortar ciment-nisip M10", thickness: 50 },
      { material: "Beton armat", thickness: 250 },
      { material: "Sticlă celulară T4+ (perete grad)", thickness: 150 },
      { material: "Bitum (membrană)", thickness: 5 },
      { material: "Tencuială silicatică (exterior)", thickness: 5 },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // AT — atic / parapet — completare diverse foc + epoci
  // ════════════════════════════════════════════════════════════════════
  {
    id: "AT-vata-bazaltica-150-foc",
    elementType: "AT",
    label: "Atic vată bazaltică 150 mm (clădire ≥28 m, P118)",
    shortLabel: "Atic VM 150",
    description: "Atic clădire publică sau ≥28 m — vată bazaltică incombustibilă conform P118/2013.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.22,
    uRange: { min: 0.19, max: 0.26 },
    uClass: "B",
    fireClass: "A1",
    tags: ["nzeb", "public", "foc", "vata-minerala"],
    source: "P118/2013 art. 2.5.7",
    notes: "Capac inox sau membrană SBS pentru protecție UV.",
    layers: [
      { material: "Tablă zincată", thickness: 0.6 },
      { material: "Vată bazaltică Rockwool Frontrock MAX E", thickness: 150 },
      { material: "Beton armat", thickness: 200 },
      { material: "Vată bazaltică Rockwool Frontrock MAX E", thickness: 50 },
      { material: "Tencuială minerală (var+ciment+pulbere marmoră)", thickness: 5 },
    ],
  },
  {
    id: "AT-clt-160-fibrolemn",
    elementType: "AT",
    label: "Atic CLT + fibrolemn 160 mm (case lemn nZEB)",
    shortLabel: "Atic CLT eco",
    description: "Atic case lemn moderne — panou CLT structural + fibră de lemn rigidă exterior.",
    era: "nzeb-2020+",
    structure: "lemn",
    renovationStatus: "nou",
    uTypical: 0.21,
    uRange: { min: 0.19, max: 0.25 },
    uClass: "B",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "lemn", "ecologic", "clt"],
    source: "PHI Component Database 2024",
    notes: "Capac din zinc/cupru — preferat pentru estetica fațadelor lemn.",
    layers: [
      { material: "Acoperire metalică Zn-Ti (VMZinc/Rheinzink-class)", thickness: 0.7 },
      { material: "Fibră de lemn rigidă (fațadă)", thickness: 160 },
      { material: "CLT - longitudine (fibre longitudinale)", thickness: 100 },
      { material: "Fibră de lemn rigidă (fațadă)", thickness: 60 },
      { material: "Tencuială silicatică (exterior)", thickness: 5 },
    ],
  },
  {
    id: "AT-parapet-pre1990-bca-30",
    elementType: "AT",
    label: "Parapet pre-1990 BCA 30 cm (audit blocuri)",
    shortLabel: "Parapet BCA pre1990",
    description: "Parapet bloc anii 70-80 — BCA 30 cm cu mortar ciment, fără izolație. Punte majoră vară-iarnă.",
    era: "1970-1990",
    structure: "panou-mare",
    renovationStatus: "existent",
    uTypical: 0.95,
    uRange: { min: 0.80, max: 1.10 },
    uClass: "E",
    fireClass: "A1",
    tags: ["audit", "bloc", "1970-1990", "parapet"],
    source: "C 107/3-2005 Anexa A",
    notes: "Eligibil reabilitare PNRR — adăugare ETICS 100 mm + capac.",
    layers: [
      { material: "Tencuială silicatică (exterior)", thickness: 5 },
      { material: "BCA Siporex 500 (λ=0.13)", thickness: 300 },
      { material: "Tencuială mortar drișcuit (renovare)", thickness: 25 },
    ],
  },
  {
    id: "AT-eps-200-ph-premium",
    elementType: "AT",
    label: "Atic Passivhaus EPS 200 mm + retur izolație 360°",
    shortLabel: "Atic PH 200",
    description: "Atic Passivhaus cu retur izolație 360° (peste, pe față exterioară și interioară) — eliminare totală punte termică.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.16,
    uRange: { min: 0.14, max: 0.19 },
    uClass: "A",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "passivhaus", "premium"],
    source: "PHI Component Database; PassREg",
    notes: "Ψ_atic ≤ 0.01 W/(m·K) cu retur 360° conform PHI.",
    layers: [
      { material: "Tablă zincată", thickness: 0.6 },
      { material: "Polistiren grafitat EPS Neo", thickness: 200 },
      { material: "Beton armat", thickness: 150 },
      { material: "Polistiren grafitat EPS Neo", thickness: 80 },
      { material: "Tencuială silicatică (exterior)", thickness: 5 },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // AC_VERDE — acoperiș verde — completare epoci
  // ════════════════════════════════════════════════════════════════════
  {
    id: "AC-verde-blue-roof",
    elementType: "AC_VERDE",
    label: "Acoperiș verde + Blue roof (retenție apă pluvială)",
    shortLabel: "Verde+Blue roof",
    description: "Combinat verde extensiv + sistem retenție apă (blue roof) — controlul scurgerii pluviale urbane.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.18,
    uRange: { min: 0.16, max: 0.22 },
    uClass: "A",
    fireClass: "B-s1,d0",
    tags: ["nzeb", "verde", "blue-roof", "urban", "drenaj"],
    source: "FLL Green Roof Guidelines 2018; SuDS Manual UK",
    notes: "Capacitate retenție 60-80 L/m² — reducere debit pluvial cu 70%.",
    layers: [
      { material: "Substrat acoperis verde (extensive, δ=80mm)", thickness: 120 },
      { material: "Geotextil", thickness: 5 },
      { material: "Strat de drenaj acoperis verde (granulat argila)", thickness: 50 },
      { material: "Geotextil", thickness: 3 },
      { material: "Membrană EPDM", thickness: 1.5 },
      { material: "EPS 200 (trafic greu)", thickness: 200 },
      { material: "Folie PE", thickness: 0.2 },
      { material: "Beton armat", thickness: 250 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "AC-verde-xps-200-ph",
    elementType: "AC_VERDE",
    label: "Verde extensiv XPS 200 mm (Passivhaus)",
    shortLabel: "Verde XPS PH",
    description: "Acoperiș verde Passivhaus cu XPS 200 mm rezistent compresie sub substrat extensiv.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.16,
    uRange: { min: 0.14, max: 0.19 },
    uClass: "A",
    fireClass: "B-s1,d0",
    tags: ["nzeb", "passivhaus", "verde", "premium"],
    source: "PHI Component Database; FLL Guidelines",
    notes: "XPS 300 kPa — soluție stabilă pentru substrat hidrofobic + apă.",
    layers: [
      { material: "Substrat acoperis verde (extensive, δ=80mm)", thickness: 80 },
      { material: "Geotextil", thickness: 5 },
      { material: "Strat de drenaj acoperis verde (granulat argila)", thickness: 30 },
      { material: "Geocompozit dren (polietilenă + geotextil)", thickness: 8 },
      { material: "Membrană EPDM", thickness: 1.5 },
      { material: "XPS 300 (fundații)", thickness: 200 },
      { material: "Bitum modificat APP", thickness: 4 },
      { material: "Beton armat", thickness: 250 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "AC-verde-biodivers-pasari",
    elementType: "AC_VERDE",
    label: "Verde biodivers (mediu hibrid păsări/insecte)",
    shortLabel: "Verde biodivers",
    description: "Acoperiș verde pentru biodiversitate — substrat 100-200 mm cu microhabitate (pietre, lemn mort, vegetație xerofită).",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.17,
    uRange: { min: 0.15, max: 0.20 },
    uClass: "A",
    fireClass: "B-s1,d0",
    tags: ["nzeb", "verde", "biodivers", "ecologic", "urban"],
    source: "FLL Biodiverse Roof; Living Roofs UK",
    notes: "Punctaj BREEAM/DGNB pentru biodiversitate — 5-10 puncte category Land Use & Ecology.",
    layers: [
      { material: "Substrat acoperis verde (intensive, δ=200mm)", thickness: 180 },
      { material: "Geotextil", thickness: 5 },
      { material: "Strat de drenaj acoperis verde (granulat argila)", thickness: 60 },
      { material: "Geocompozit dren (polietilenă + geotextil)", thickness: 8 },
      { material: "Membrană EPDM", thickness: 1.5 },
      { material: "Polistiren expandat EPS 100", thickness: 200 },
      { material: "Bitum modificat APP", thickness: 4 },
      { material: "Beton armat", thickness: 250 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // PR — perete spre spațiu neîncălzit — completare
  // ════════════════════════════════════════════════════════════════════
  {
    id: "PR-pre1970-zid-30-casa-scarii",
    elementType: "PR",
    label: "Perete casa scării pre-1970 — zidărie 30 cm (audit)",
    shortLabel: "PR pre1970 30",
    description: "Perete între apartament și casa scărilor în bloc 1900-1970 — cărămidă 30 cm fără izolație.",
    era: "pre1970",
    structure: "zidarie",
    renovationStatus: "existent",
    uTypical: 1.55,
    uRange: { min: 1.40, max: 1.75 },
    uClass: "F",
    fireClass: "A1",
    tags: ["audit", "pre-1970", "casa-scarii", "bloc"],
    source: "C 107/3-2005 Anexa A",
    notes: "Tau=0.8 (factor reducere flux către spațiu neîncălzit). Eligibil retrofit cu IWI.",
    layers: [
      { material: "Tencuială de ipsos", thickness: 15 },
      { material: "Cărămidă plină", thickness: 300 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PR-bca-25-bloc-1985-casa-scarii",
    elementType: "PR",
    label: "PR casa scării bloc 1985 — BCA 25 cm",
    shortLabel: "PR BCA 25 bloc",
    description: "Perete intern către casa scării bloc 1980-1990 — BCA 25 cm.",
    era: "1970-1990",
    structure: "panou-mare",
    renovationStatus: "existent",
    uTypical: 1.05,
    uRange: { min: 0.90, max: 1.20 },
    uClass: "E",
    fireClass: "A1",
    tags: ["audit", "1970-1990", "casa-scarii", "bloc"],
    source: "C 107/3-2005 Anexa A",
    notes: "Eligibil IWI cu silicat de calciu pentru control condens.",
    layers: [
      { material: "Tencuială de ipsos", thickness: 15 },
      { material: "BCA Siporex 500 (λ=0.13)", thickness: 250 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PR-iwi-calsil-50-casa-scarii",
    elementType: "PR",
    label: "PR retrofit cu IWI silicat de calciu 50 mm",
    shortLabel: "PR IWI CalSil 50",
    description: "Retrofit perete casa scării cu izolație interioară silicat de calciu 50 mm — control condens.",
    era: "nzeb-2020+",
    structure: "zidarie",
    renovationStatus: "renovat",
    uTypical: 0.55,
    uRange: { min: 0.48, max: 0.65 },
    uClass: "D",
    fireClass: "A1",
    tags: ["renovat", "iwi", "silicat", "retrofit"],
    source: "Multipor / Skamol catalogue 2023; PassREg IWI",
    notes: "Soluție higroscopică — sigur fără barieră vapori. Optim 25-50 mm.",
    layers: [
      { material: "Tencuială lut-bălegar (clay-dung plaster)", thickness: 5 },
      { material: "Placă silicat de calciu interioară (Skamol/Multipor-class)", thickness: 50 },
      { material: "Cărămidă plină", thickness: 300 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PR-CLT-mass-bloc-nzeb",
    elementType: "PR",
    label: "PR CLT 80 mm — bloc lemn modern",
    shortLabel: "PR CLT 80",
    description: "Perete între apartamente lemn (case 1+2) cu CLT structural 80 mm + finisaj gips.",
    era: "nzeb-2020+",
    structure: "lemn",
    renovationStatus: "nou",
    uTypical: 0.85,
    uRange: { min: 0.75, max: 0.95 },
    uClass: "E",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "clt", "lemn", "casa-scarii"],
    source: "SR EN 16351; PHI",
    notes: "Mass timber — masă termică ridicată, izolație fonică REI 60 minim.",
    layers: [
      { material: "Gips-carton RF (Rigips rezistent foc 12.5mm)", thickness: 12.5 },
      { material: "CLT (Cross Laminated Timber)", thickness: 80 },
      { material: "Gips-carton RF (Rigips rezistent foc 12.5mm)", thickness: 12.5 },
    ],
  },
  {
    id: "PR-zidarie-vm-100-renovat",
    elementType: "PR",
    label: "PR zidărie + VM 100 mm — renovare bloc",
    shortLabel: "PR zid VM 100",
    description: "Retrofit perete casa scării bloc cu vată minerală 100 mm pe față încălzită.",
    era: "2010-2020",
    structure: "zidarie",
    renovationStatus: "renovat",
    uTypical: 0.32,
    uRange: { min: 0.28, max: 0.38 },
    uClass: "C",
    fireClass: "A1",
    tags: ["renovat", "vata-minerala", "casa-scarii"],
    source: "Mc 001-2022 Tab. 2.4",
    notes: "Atinge nZEB renovare (Tab. 2.4) — soluție populară pentru reabilitare bloc.",
    layers: [
      { material: "Gips-carton", thickness: 12.5 },
      { material: "Vată minerală bazaltică", thickness: 100 },
      { material: "BCA Siporex 500 (λ=0.13)", thickness: 250 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // PS — perete subteran — completare
  // ════════════════════════════════════════════════════════════════════
  {
    id: "PS-pre1970-piatra-uzina",
    elementType: "PS",
    label: "PS subsol piatră 60 cm — case interbelice (audit)",
    shortLabel: "PS piatră pre1970",
    description: "Perete subteran case interbelice și hale industriale — piatră 60 cm cu mortar var.",
    era: "pre1970",
    structure: "zidarie",
    renovationStatus: "existent",
    uTypical: 1.40,
    uRange: { min: 1.20, max: 1.60 },
    uClass: "F",
    fireClass: "A1",
    tags: ["audit", "pre-1970", "patrimoniu", "subsol"],
    source: "C 107/5-2005 Anexa A",
    notes: "Verificare umiditate ascensională — necesar drenaj perimetru înainte de IWI.",
    layers: [
      { material: "Sol argilos (conținut apă ridicat)", thickness: 1000 },
      { material: "Piatră de calcar (calc. compactat)", thickness: 600 },
      { material: "Tencuială mortar drișcuit (renovare)", thickness: 30 },
    ],
  },
  {
    id: "PS-bca-na-100-1990",
    elementType: "PS",
    label: "PS subsol BCA 30 cm — case 1990-2010 (existent)",
    shortLabel: "PS BCA pre2010",
    description: "Perete subteran case construite 1990-2010 — BCA 30 cm fără izolație externă.",
    era: "1990-2010",
    structure: "cadre-ba",
    renovationStatus: "existent",
    uTypical: 0.85,
    uRange: { min: 0.75, max: 0.95 },
    uClass: "E",
    fireClass: "A1",
    tags: ["audit", "1990-2010", "subsol", "popular"],
    source: "C 107/5-2005",
    notes: "Risc condens când subsol incalzit slab — verificare dewpoint în iarnă.",
    layers: [
      { material: "Sol argilos (conținut apă ridicat)", thickness: 800 },
      { material: "Membrană EPDM", thickness: 1 },
      { material: "BCA (beton celular autoclavizat)", thickness: 300 },
      { material: "Tencuială mortar drișcuit (renovare)", thickness: 20 },
    ],
  },
  {
    id: "PS-XPS-150-PH-pereti-subsol",
    elementType: "PS",
    label: "PS Passivhaus XPS 150 mm pe față exterioară",
    shortLabel: "PS XPS 150 PH",
    description: "Perete subteran Passivhaus cu XPS 150 mm protejat cu membrană drenantă HDPE.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.18,
    uRange: { min: 0.16, max: 0.22 },
    uClass: "A",
    fireClass: "A1",
    tags: ["nzeb", "passivhaus", "subsol", "premium"],
    source: "PHI Component Database; SR EN ISO 13370",
    notes: "Membrană drenantă HDPE protejează XPS de presiune sol și permite drenaj apă.",
    layers: [
      { material: "Sol argilos (conținut apă ridicat)", thickness: 800 },
      { material: "Geocompozit dren (polietilenă + geotextil)", thickness: 8 },
      { material: "Membrana drenantă HDPE", thickness: 1 },
      { material: "XPS 300 (fundații)", thickness: 150 },
      { material: "Membrană bentonitică (geosynthetic clay liner)", thickness: 6 },
      { material: "Beton armat", thickness: 300 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PS-foamglas-200-monumental",
    elementType: "PS",
    label: "PS FOAMGLAS 200 mm — monumental, eternal",
    shortLabel: "PS foamglas",
    description: "Perete subteran monumental cu sticlă celulară FOAMGLAS — durată >100 ani, anti-radon.",
    era: "nzeb-2020+",
    structure: "cadre-ba",
    renovationStatus: "nou",
    uTypical: 0.20,
    uRange: { min: 0.18, max: 0.24 },
    uClass: "B",
    fireClass: "A1",
    tags: ["nzeb", "premium", "foamglas", "monumental", "antiradon"],
    source: "Pittsburgh Corning Catalogue 2023",
    notes: "FOAMGLAS — sigur la radon, izolant fără degradare în sol >100 ani.",
    layers: [
      { material: "Sol argilos (conținut apă ridicat)", thickness: 800 },
      { material: "Geocompozit dren (polietilenă + geotextil)", thickness: 10 },
      { material: "Sticlă celulară T4+ (perete grad)", thickness: 200 },
      { material: "Bitum (membrană)", thickness: 5 },
      { material: "Beton armat", thickness: 300 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // PI — perete interior (între spații încălzite) — completare
  // ════════════════════════════════════════════════════════════════════
  {
    id: "PI-zidarie-15-traditional",
    elementType: "PI",
    label: "PI zidărie 15 cm — case 1970-1990 tradițional",
    shortLabel: "PI zidărie 15",
    description: "Perete interior despărțitor între camere — cărămidă 15 cm cu mortar ciment.",
    era: "1970-1990",
    structure: "zidarie",
    renovationStatus: "existent",
    uTypical: 1.95,
    uRange: { min: 1.70, max: 2.20 },
    uClass: "G",
    fireClass: "A1",
    tags: ["audit", "1970-1990", "ro-clasic"],
    source: "C 107/3-2005",
    notes: "Element non-anvelopă (tau=0) — masă termică pentru protecție vară.",
    layers: [
      { material: "Tencuială de ipsos", thickness: 15 },
      { material: "Cărămidă plină", thickness: 150 },
      { material: "Tencuială de ipsos", thickness: 15 },
    ],
  },
  {
    id: "PI-gips-fibros-double-acustic",
    elementType: "PI",
    label: "PI gips-carton dublu W112 acustic (premium)",
    shortLabel: "PI GK W112 acustic",
    description: "Perete despărțitor sistem Knauf W112 — gips-carton dublu pe ambele fețe + cavitate VM 100 mm. Rw≥55 dB.",
    era: "nzeb-2020+",
    structure: "metal",
    renovationStatus: "nou",
    uTypical: 0.45,
    uRange: { min: 0.40, max: 0.52 },
    uClass: "D",
    fireClass: "A2-s1,d0",
    tags: ["nzeb", "metal", "acustic", "knauf"],
    source: "Knauf W112 datasheet 2024; SR EN ISO 717-1",
    notes: "Performanță acustică Rw=55-60 dB pentru hoteluri, birouri.",
    layers: [
      { material: "Gips-carton Knauf Blue (standard 12.5mm)", thickness: 12.5 },
      { material: "Gips-carton Knauf Blue (standard 12.5mm)", thickness: 12.5 },
      { material: "Profil oțel zincat (C/U structural)", thickness: 1 },
      { material: "Vată minerală bazaltică", thickness: 100 },
      { material: "Profil oțel zincat (C/U structural)", thickness: 1 },
      { material: "Gips-carton Knauf Blue (standard 12.5mm)", thickness: 12.5 },
      { material: "Gips-carton Knauf Blue (standard 12.5mm)", thickness: 12.5 },
    ],
  },
  {
    id: "PI-CLT-100-aparent-eco",
    elementType: "PI",
    label: "PI CLT 100 mm aparent (case lemn moderne)",
    shortLabel: "PI CLT 100 vis",
    description: "Perete interior CLT vizibil — 3 straturi lemn cu finisaj transparent ulei vegetal.",
    era: "nzeb-2020+",
    structure: "lemn",
    renovationStatus: "nou",
    uTypical: 1.20,
    uRange: { min: 1.05, max: 1.40 },
    uClass: "F",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "clt", "ecologic", "estetic"],
    source: "SR EN 16351; KLH catalogue",
    notes: "Element non-anvelopă — masă termică + estetică naturală + acustică.",
    layers: [
      { material: "CLT (Cross Laminated Timber)", thickness: 100 },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // US — uși opace exterioare — completare
  // ════════════════════════════════════════════════════════════════════
  {
    id: "US-stejar-traditional-1900",
    elementType: "US",
    label: "Ușă stejar masiv 60 mm — patrimoniu (pre-1970)",
    shortLabel: "US stejar 60",
    description: "Ușă exterioară stejar masiv 60 mm — case interbelice și anterior, fără izolație.",
    era: "pre1970",
    structure: "lemn",
    renovationStatus: "existent",
    uTypical: 2.50,
    uRange: { min: 2.20, max: 2.85 },
    uClass: "G",
    fireClass: "B-s2,d0",
    tags: ["audit", "pre-1970", "patrimoniu", "stejar"],
    source: "SR EN 14351-1; STAS 9322-71",
    notes: "Patrimoniu — restaurare cu garnituri etanșare + dublură interioară.",
    layers: [
      { material: "Lemn tare (stejar)", thickness: 60 },
    ],
  },
  {
    id: "US-PVC-PH-Ud-08-passive",
    elementType: "US",
    label: "Ușă PVC Passivhaus Ud=0.8 W/m²K (premium)",
    shortLabel: "US PVC PH Ud08",
    description: "Ușă PVC Passivhaus certificată — Ud≤0.8 W/m²K cu miez PIR + garnituri triple.",
    era: "nzeb-2020+",
    structure: "metal",
    renovationStatus: "nou",
    uTypical: 0.80,
    uRange: { min: 0.70, max: 0.95 },
    uClass: "A+",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "passivhaus", "premium", "pvc"],
    source: "PHI Component Database; SR EN 14351-1",
    notes: "Componentă certificată Passivhaus — verificat n50 cu blower door 0.6 1/h.",
    layers: [
      { material: "PVC rigid (profile, evi)", thickness: 5 },
      { material: "PIR cu folie alu", thickness: 80 },
      { material: "PVC rigid (profile, evi)", thickness: 5 },
    ],
  },
  {
    id: "US-aluminiu-securitate-PU-60",
    elementType: "US",
    label: "Ușă aluminiu securitate PU 60 mm (clasa RC3)",
    shortLabel: "US Alu RC3",
    description: "Ușă aluminiu cu rupere termică + miez PU 60 mm + clasa securitate RC3 (anti-efracție).",
    era: "nzeb-2020+",
    structure: "metal",
    renovationStatus: "nou",
    uTypical: 1.20,
    uRange: { min: 1.10, max: 1.40 },
    uClass: "B",
    fireClass: "A2-s1,d0",
    tags: ["nzeb", "metal", "securitate", "rc3", "aluminiu"],
    source: "Schüco AD UP 75 SI datasheet; SR EN 1627",
    notes: "Securitate clasa RC3 — rezistă atacuri 5 minute scule profesionale.",
    layers: [
      { material: "Aluminiu", thickness: 3 },
      { material: "Spumă poliuretanică (PUR)", thickness: 60 },
      { material: "Aluminiu", thickness: 3 },
    ],
  },
  {
    id: "US-fibra-sticla-PU-60-modern",
    elementType: "US",
    label: "Ușă fibră de sticlă composit PU 60 mm",
    shortLabel: "US fibrosticlă PU",
    description: "Ușă composit GRP/FRP cu miez PU 60 mm — rezistență chimică și UV ridicată.",
    era: "nzeb-2020+",
    structure: "metal",
    renovationStatus: "nou",
    uTypical: 1.10,
    uRange: { min: 0.95, max: 1.30 },
    uClass: "B",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "composite", "frp", "modern"],
    source: "Therma-Tru Smooth-Star; SR EN 14351-1",
    notes: "Composite GRP — durabilitate ≥30 ani fără mentenanță vopsea.",
    layers: [
      { material: "Fibră de sticlă compozit (GRP/FRP panel)", thickness: 4 },
      { material: "Spumă poliuretanică (PUR)", thickness: 60 },
      { material: "Fibră de sticlă compozit (GRP/FRP panel)", thickness: 4 },
    ],
  },
  {
    id: "US-otel-foc-EI60-bloc",
    elementType: "US",
    label: "Ușă oțel anti-foc EI60 + vată bazaltică (bloc public)",
    shortLabel: "US oțel EI60",
    description: "Ușă oțel rezistență la foc EI60 cu miez vată bazaltică — clădiri publice și blocuri.",
    era: "nzeb-2020+",
    structure: "metal",
    renovationStatus: "nou",
    uTypical: 1.40,
    uRange: { min: 1.20, max: 1.65 },
    uClass: "C",
    fireClass: "A1",
    tags: ["nzeb", "metal", "foc", "ei60", "public"],
    source: "P118/2013 art. 3.5; SR EN 1634-1",
    notes: "EI60 = etanșeitate + izolare 60 minute la foc. Obligatoriu casa scării bloc.",
    layers: [
      { material: "Oțel", thickness: 3 },
      { material: "Vată bazaltică HD", thickness: 50 },
      { material: "Oțel", thickness: 3 },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // UN — uși spre spațiu neîncălzit — completare
  // ════════════════════════════════════════════════════════════════════
  {
    id: "UN-otel-clasic-bloc-1985",
    elementType: "UN",
    label: "Ușă oțel bloc 1985 — vată minerală 30 mm (audit)",
    shortLabel: "UN oțel bloc",
    description: "Ușă oțel apartament către casa scărilor bloc anii 80 — vată minerală 30 mm + lacă vinil.",
    era: "1970-1990",
    structure: "metal",
    renovationStatus: "existent",
    uTypical: 2.30,
    uRange: { min: 2.10, max: 2.60 },
    uClass: "F",
    fireClass: "A2-s1,d0",
    tags: ["audit", "1970-1990", "bloc", "ro-clasic"],
    source: "STAS 466-78",
    notes: "Tipic ușă tip Drumul Taberei — 30 mm VM, garnituri uzate.",
    layers: [
      { material: "Oțel", thickness: 1.5 },
      { material: "Vată minerală bazaltică", thickness: 30 },
      { material: "Oțel", thickness: 1.5 },
    ],
  },
  {
    id: "UN-PVC-vata-30-renovat",
    elementType: "UN",
    label: "Ușă PVC vată 30 mm — apartament renovat",
    shortLabel: "UN PVC 30",
    description: "Ușă PVC apartament către casa scării — miez vată minerală 30 mm + 5 puncte încuietoare.",
    era: "nzeb-2020+",
    structure: "metal",
    renovationStatus: "renovat",
    uTypical: 1.45,
    uRange: { min: 1.30, max: 1.65 },
    uClass: "C",
    fireClass: "B-s2,d0",
    tags: ["renovat", "pvc", "bloc"],
    source: "SR EN 14351-1",
    notes: "Soluție populară post-2010 — îmbunătățire majoră vs. ușă oțel veche.",
    layers: [
      { material: "PVC rigid (profile, evi)", thickness: 5 },
      { material: "Vată minerală bazaltică", thickness: 30 },
      { material: "PVC rigid (profile, evi)", thickness: 5 },
    ],
  },
  {
    id: "UN-aluminiu-vata-50-modern",
    elementType: "UN",
    label: "Ușă aluminiu vată 50 mm — bloc modern",
    shortLabel: "UN Alu vata 50",
    description: "Ușă aluminiu apartament-casa scării bloc nou — vată minerală 50 mm + clasa RC2.",
    era: "nzeb-2020+",
    structure: "metal",
    renovationStatus: "nou",
    uTypical: 1.20,
    uRange: { min: 1.05, max: 1.40 },
    uClass: "B",
    fireClass: "A2-s1,d0",
    tags: ["nzeb", "aluminiu", "bloc", "rc2"],
    source: "Schüco; SR EN 1627",
    notes: "Securitate RC2 + acustică Rw=42 dB.",
    layers: [
      { material: "Aluminiu", thickness: 3 },
      { material: "Vată bazaltică HD", thickness: 50 },
      { material: "Aluminiu", thickness: 3 },
    ],
  },
  {
    id: "UN-lemn-vata-40-eco",
    elementType: "UN",
    label: "Ușă lemn modern + vată 40 mm (eco)",
    shortLabel: "UN lemn vata",
    description: "Ușă lemn brad/molid masiv + miez vată minerală 40 mm — case lemn moderne.",
    era: "nzeb-2020+",
    structure: "lemn",
    renovationStatus: "nou",
    uTypical: 1.30,
    uRange: { min: 1.15, max: 1.50 },
    uClass: "B",
    fireClass: "B-s2,d0",
    tags: ["nzeb", "lemn", "ecologic"],
    source: "SR EN 14351-1",
    notes: "Compatibilă cu case CLT/timber frame — estetică naturală.",
    layers: [
      { material: "Lemn moale (brad/molid)", thickness: 22 },
      { material: "Vată minerală bazaltică", thickness: 40 },
      { material: "Lemn moale (brad/molid)", thickness: 22 },
    ],
  },
];

// ── Validare materiale ───────────────────────────────────────────────────────
console.log("Total entries to add:", NEW_SOLUTIONS.length);

const errors = [];
const seenIds = new Set();
for (const sol of NEW_SOLUTIONS) {
  // Dublarea de id
  if (existingIds.has(sol.id)) errors.push(`DUPLICATE EXISTING ID: ${sol.id}`);
  if (seenIds.has(sol.id)) errors.push(`DUPLICATE NEW ID: ${sol.id}`);
  seenIds.add(sol.id);

  // Materiale
  if (!sol.layers || !sol.layers.length) {
    errors.push(`${sol.id}: no layers`);
    continue;
  }
  for (const l of sol.layers) {
    if (!materialNames.has(l.material)) {
      errors.push(`${sol.id}: missing material → "${l.material}"`);
    }
    if (typeof l.thickness !== "number" || l.thickness <= 0) {
      errors.push(`${sol.id}: invalid thickness for "${l.material}": ${l.thickness}`);
    }
  }

  // Câmpuri obligatorii
  const required = ["id", "elementType", "label", "shortLabel", "description", "era", "structure", "renovationStatus", "uTypical", "uRange", "uClass", "fireClass", "tags", "source", "notes", "layers"];
  for (const k of required) {
    if (!(k in sol)) errors.push(`${sol.id}: missing field "${k}"`);
  }
}

if (errors.length) {
  console.error("\n❌ VALIDATION ERRORS:\n" + errors.join("\n"));
  process.exit(1);
}

console.log("✅ All", NEW_SOLUTIONS.length, "entries valid (materials, ids, fields).");

// ── Merge & write ───────────────────────────────────────────────────────────
const merged = {
  ...existing,
  version: "2.0.0",
  lastUpdated: new Date().toISOString().split("T")[0],
  solutions: [...existing.solutions, ...NEW_SOLUTIONS],
};

fs.writeFileSync(SOLUTIONS_PATH, JSON.stringify(merged, null, 2) + "\n", "utf-8");
console.log("📦 Wrote", merged.solutions.length, "total solutions to typicalSolutions.json");
console.log("Version:", merged.version, "→ lastUpdated:", merged.lastUpdated);

// Stats
const stats = {};
NEW_SOLUTIONS.forEach(s => {
  stats[s.elementType] = (stats[s.elementType] || 0) + 1;
});
console.log("\nNew entries by element type:");
Object.entries(stats).sort().forEach(([k, v]) => console.log(`  ${k}: +${v}`));
